[build]
  # Set the publish directory to the dist folder where your static files are
  publish = "dist"
  command = "echo Building Functions"

[functions]
  # Ensure the functions directory is correctly set to where your Netlify functions are
  directory = "netlify/functions" 
  external_node_modules = ["express", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  # Redirect all API requests to the serverless function
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true
