on:
  schedule:
    - cron: '0 0 * * *'  # runs once every 24 hours at midnight UTC

jobs:
  health-check:
  runs-on: ubuntu-20.04
  steps:
    - name: Perform health check
      uses: Jtalk/url-health-check-action@v4
      with:
        url: 'https://fullstack-p11-pokedex.netlify.app'
        retry: 2 
        interval: 5 
        timeout: 10